SGCLA/SGCLA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("SGCLAapp/", include("SGCLAapp.urls")),
]

SGCLA/SGCLAapp/urls.py
from django.urls import path
from . import views

app_name = "SGCLA"
urlpatterns = [
    path("", views.index, name="index"),
    path("<int:livro_id>/detalhes/" ,views.detalhes, name="detalhes"),
    path("resultadoDaBusca/<str:busca>", views.resultadoDaBusca, name="buscar"),
    path("adicionarUmLivroRota/", views.adicionarUmLivroRota, name="adicionarUmLivroRota"),
    path("adicionarUmLivro/", views.adicionarUmLivro, name="adicionarUmLivro")
]

SGCLA/SGCLAapp/models.py
from django.db import models
import datetime
# Create your models here.
class Livro(models.Model):
    titulo = models.CharField("Título do Livro", max_length=200)
    genero = models.CharField("Gênero textual", max_length=20)
    autor = models.CharField("Autor(res)",max_length=200)
    editora = models.CharField("Editora",max_length=150)
    anoPublicacao = models.DateTimeField("Data de publicação")
    unidades = models.IntegerField(default=1)

    def __str__(self):
        return self.titulo + " - " + str(self.autor)
    

class Usuario(models.Model):
    pNome = models.CharField("Primeiro nome",max_length=200)
    uNome = models.CharField("Sobrenome",max_length=200)
    dataNasc = models.DateField("Data de Nascimento")
    livros = models.ManyToManyField(Livro, through = "LivrosAlugados")

    def __str__(self):
        return self.pNome + ' '+ self.uNome

class LivrosAlugados(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    livro = models.ForeignKey(Livro,on_delete=models.CASCADE)
    dataDevolucao = models.DateTimeField()
    dataEmprestado = models.DateTimeField()
    nota = models.CharField("Observação", max_length=200,default="")

    def aluguelNormal(self):
        return self.dataEmprestado + datetime.timedelta(days = 7)

    def aluguelExtendido(self):
        return self.dataEmprestado + datetime.timedelta(days = 15)

SGCLA/SGCLAapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from .models import Livro, LivrosAlugados
from django.db.models import Q
from django.urls import reverse
from django.template import loader
from django.core.exceptions import ValidationError

# Create your views here.

def index(request):
    livros = Livro.objects.all().order_by("titulo")
    template = loader.get_template("SGCLAapp/index.html")
    context = {
        "livros":livros
    }
    return HttpResponse(template.render(context, request))

def detalhes(request,livro_id):
    livro = get_object_or_404(Livro, pk = livro_id)
    alugados = LivrosAlugados.objects.filter(livro_id = livro_id)
    livrosDisponiveis = livro.unidades - alugados.count()
    return render(request, "SGCLAapp/detalhes.html",{
        "livro": livro,
        "alugados": alugados,
        "disponiveis":livrosDisponiveis,
    })

def resultadoDaBusca(request,busca):

        busca = request.GET["titulo"]
        livros = Livro.objects.filter( Q(titulo__icontains = busca) | Q(autor__icontains = busca))
        if livros:
            statusCode = 201
        else:
            statusCode = 404
        return render(
            request,
            "SGCLAapp/index.html",
            {
                "livros":livros,
                "busca" : True
            },
            status = int(statusCode)
        )
def adicionarUmLivroRota(request):
    template = loader.get_template("SGCLAapp/adicionarUmLivro.html")
    contexto = {"fakeIt_tillYouMakeIt" : True}
    return  HttpResponse(template.render(contexto, request))

def adicionarUmLivro(request):
     
    if request.POST["unidades"]:
        entradasInvalidas = ["True", "None", "False"]

        if request.POST["unidades"] in entradasInvalidas:
            raise ValidationError("Seu filho da ****",500)
        
        elif int(request.POST["unidades"]) <= 0:
            raise ValidationError("As unidades precisam ser um número válido maior que 0.", 500)
    
        else:
            pass
        
    livro, inserido = Livro.objects.get_or_create(
        titulo=request.POST["titulo"],
        genero=request.POST["genero"],
        autor=request.POST["autor"],
        editora=request.POST["editora"],
        anoPublicacao=request.POST["anoPublicacao"],      
        unidades=int(request.POST["unidades"])
    )

    if inserido:
        return HttpResponseRedirect(
            reverse(
                "SGCLA:detalhes",
                kwargs={
                    "livro_id":livro.id,
                    }
            )
        )
    
    else:
        return render(
                request,
                "SGCLAapp/detalhe.html",
                {
                    "livro":livro,
                    "mensagemDeErro":"Este livro já consta na base de dados"
                },
            )

SGCLA/SGCLAapp/templates/SGCLAapp/adicionarUmLivro.html
{% load static %}
<link rel="stylesheet" href="{% static 'SGCLAapp/estilo.css' %}"/>
<a href="{% url 'SGCLA:index' %}">Voltar ao início</a>

<h1>Adicionar um livro</h1>

<form action="{%url 'SGCLA:adicionarUmLivro'%}" method="POST">
    {%csrf_token%}
    <label for="titulo">Título do livro:</label>
    <input type="text" name="titulo" id="titulo" placeholder="Ex: O pequeno príncipe">

    <label for="autor"> Autor do livro <small>Caso de múltiplos autores separar por vírgulas ex: Franz Kafka, J.K. Rowling</small>:</label>
    <input type="text" name="autor" id="autor" placeholder="Ex: C.S. Lewis, Fausto Silva">

    <label for="genero">Gênero:</label>
    <input type="text" name="genero" id="genero" placeholder="Ex: Suspense">

    <label for="editora">Editora:</label>
    <input type="text" name="editora" id="editora" placeholder="Ex: Abril - Clássicos">

    <label for="anoPublicacao">Data de Publicação:</label>
    <input type="date" name="anoPublicacao" id="anoPublicacao" placeholder="Ex: 15/11/1889">

    <label for="unidades">Unidades disponíveis:</label>
    <input type="number" name="unidades" id="unidades" placeholder="Ex: 5" value="0">

    <label for="enviar">Botão de enviar formulário</label>
    <input type="submit" id="enviar" value="Clique aqui para adcionar este livro">
</form>

SGCLA/SGCLAapp/templates/SGCLAapp/detalhes.html
{% load static %}
<link rel="stylesheet" href="{% static 'SGCLAapp/estilo.css' %}"/>

<a href="{%url 'SGCLA:index'%}"> Voltar ao Início</a>
<h1>Livro: {{livro.titulo}}</h1>
<p>Autor: {{livro.autor}}</p>
<p>Editora: {{livro.editora}}</p>
<small>Gênero:{{livro.genero}}</small>
<p>Publicação do livro:{{livro.anoPublicacao}}</p>
<p>Unidades no total: {{livro.unidades}}</p>
<p>Unidades Disponíveis: {{disponiveis}}</p>

<table>
    <h1>Livros Emprestados</h1>
    <tr>
        <th>Data Emprestado</th>
        <th>Data Devolução</th>
        <th>Cliente</th>
    </tr>
    {%for a in alugados%}
    <tr>

        <td>
            {{a.dataEmprestado}}
        </td>
        <td>
            {{a.dataDevolucao}}
        </td>
        <td>
            {{a.usuario}}
        </td>
    </tr>
        {%endfor%}
</table>

SGCLA/SGCLAapp/templates/SGCLAapp/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'SGCLAapp/estilo.css' %}"/>

<header>
    {%if busca%}
    <a href="{% url 'SGCLA:index' %}">Voltar ao início.</a>
    {%endif%}
    <a href="{%url 'SGCLA:adicionarUmLivroRota'%}">Adcionar um novo livro.</a>

    <form action="{% url 'SGCLA:buscar' 'titulo' %}" method="GET">
        {%csrf_token%}
        <label for="titulo">-Pesquisa por Título ou Autor do livro-</label>
        <br/>
        <input type="text" name="titulo" id="titulo" placeholder="Ex: Biografia Andressa Urach">
        <input type="submit" value="Pesquisar Aqui">
    </form>

</header>
{%if livros%}
    {%if busca%}
        <h1>Resultado da sua Busca:</h1>
    {%else%}
        <h1>Lista de Livros :Alfabética</h1>
    {%endif%} 
    <ul>
        {%for livro in livros%}
            <li><a href="{% url 'SGCLA:detalhes' livro.id%}">{{livro.titulo}}</a>&nbsp;&nbsp;&nbsp;{{livro.unidades}} - unidades</li>
        {%endfor%}
    </ul>
{%else%}
    <p>Nenhum Livro encontrado!</p>
{%endif%}